# Rules
rule all:
    input:
        "acc1_pe.sv",
        "acc1_array.sv",


rule apply_transform:
    input:
        "addition.mlir",
        "transform_schedule.mlir",
    output:
        "addition_transformed.mlir",
    shell:
        "mlir-opt --linalg-generalize-named-ops --transform-preload-library=transform-library-paths={input[1]} --transform-interpreter {input[0]} -o {output[0]}"


rule compile_mlir:
    input:
        "addition_transformed.mlir",
    output:
        "addition_phs.mlir",
        "acc1_pe.mlir",
    shell:
        'snax-opt -p phs-encode,phs-export-phs{{output=\\"{output[1]}\\"}} {input} -o {output[0]}'


rule create_mlir_array:
    input:
        "acc1_pe.mlir",
    output:
        "acc1_array.mlir",
    shell:
        "snax-opt -p convert-pe-to-hw{{bounds=4}} {input}  -o {output[0]}"


rule lower_mlir_array:
    input:
        "acc1_array.mlir",
    output:
        "acc1_array_hw.mlir",
    shell:
        "snax-opt -p finalize-phs-to-hw {input} | circt-opt --map-arith-to-comb --hw-flatten-modules -o {output[0]}"


rule export_verilog_array:
    input:
        "acc1_array_hw.mlir",
    output:
        "acc1_array.sv",
    shell:
        "firtool {input} --format=mlir --strip-debug-info -o {output[0]}"


rule export_verilog_pe:
    input:
        "acc1_pe.mlir",
    output:
        "acc1_pe.sv",
    shell:
        "snax-opt -p convert-pe-to-hw,finalize-phs-to-hw {input} | circt-opt --map-arith-to-comb --hw-flatten-modules | firtool --format=mlir --strip-debug-info -o {output[0]}"
