# Rules
rule all:
    input:
        "addition_out.mlir",
        "acc1_array.sv",


rule apply_transform:
    input:
        "addition.mlir",
        "transform_schedule.mlir",
    output:
        "addition_out.mlir",
        "acc1_array.sv",
    shell:
        "phsc {input[0]} {input[1]} -o {output[0]} --output-hardware {output[1]}"
