from util.snake.configs import get_snax_mac_config

config = get_snax_mac_config()

config["snaxoptflags"] = ",".join(
    [
        "dispatch-kernels",
        "set-memory-space",
        "set-memory-layout",
        "realize-memref-casts",
        "reuse-memref-allocs",
        "insert-sync-barrier",
        "dispatch-regions",
        "linalg-to-library-call",
        "snax-copy-to-dma",
        "memref-to-snax",
        "snax-to-func",
        "clear-memory-space",
    ]
)


module default_rules:
    snakefile:
        "../../util/snake/default_rules.smk"
    config:
        config


rule all:
    input:
        "func.x",
    shell:
        "{config[vltsim]} {input[0]}"


use rule * from default_rules exclude compile_simple_main as default_*


rule compile_snax_binary:
    input:
        "func.o",
        "main.o",
    output:
        "func.x",
    shell:
        "{config[ld]} {config[ldflags]} {input} -o {output}"
