from util.snake.configs import get_snax_mac_config

config = get_snax_mac_config()


module default_rules:
    snakefile:
        "../../util/snake/default_rules.smk"
    config:
        config


use rule * from default_rules as default_*


rule all:
    input:
        "func.x",
    shell:
        "{config[vltsim]} {input[0]}"
