rule all:
    input:
        "plot.svg"

rule optimize_tile_sizes:
    input:
        "resnet_layers.yaml"
    output:
        "tiled_resnet_layers.yaml",
    script:
        "optimize_tile_sizes.py"


rule plot_figure:
    input:
        "tiled_resnet_layers.yaml"
    output:
        "plot.svg",
    script:
        "plot.py"
