from util.snake.configs import get_snax_mac_config
from util.snake.paths import get_traces

config = get_snax_mac_config()
config["snaxoptflags"] = ",".join(
    [
        "dispatch-kernels",
        "set-memory-space",
        "set-memory-layout",
        "realize-memref-casts",
        "reuse-memref-allocs",
        "insert-sync-barrier",
        "dispatch-regions",
        "snax-copy-to-dma",
        "memref-to-snax",
        "snax-to-func",
        "clear-memory-space",
        "postprocess",
    ]
)


module default_rules:
    snakefile:
        "../../util/snake/default_rules.smk"
    config:
        config


use rule * from default_rules as default_*


module snax_rules:
    snakefile:
        "../../util/snake/snax.smk"
    config:
        config


use rule * from snax_rules as snax_*


files = ["simple_copy"]


# Rules
rule all:
    input:
        *get_traces(files, config["num_chips"], config["num_harts"], "dasm"),


rule compile_main:
    input:
        "main.c",
        "data.h",
    output:
        "main.o",
    shell:
        "{config[cc]} {config[cflags]} -c {input[0]}"


rule link_snax_binary:
    input:
        "simple_copy.o",
        "main.o",
        "data.o",
    output:
        "simple_copy.x",
    shell:
        "{config[ld]} {config[ldflags]} {input} -o {output}"


from gendata import create_data_files


rule generate_data:
    output:
        "data.c",
        "data.h",
    run:
        create_data_files()
