from dataclasses import dataclass

from xdsl.dialects import builtin
from xdsl.ir import MLContext
from xdsl.passes import ModulePass
from xdsl.pattern_rewriter import (
    PatternRewriter,
    PatternRewriteWalker,
    RewritePattern,
    op_type_rewrite_pattern,
)
from xdsl.traits import SymbolTable

from compiler.accelerators.registry import AcceleratorRegistry
from compiler.dialects import acc


@dataclass
class InsertAcceleratorOpPattern(RewritePattern):
    acc_op: acc.AcceleratorOp
    """
    Pattern that attaches the AcceleratorOp specified by acc_op to
    the module symbol table if the symbol wasn't there already.
    Raises a RuntimeError if the symbol is already present.
    """

    @op_type_rewrite_pattern
    def match_and_rewrite(self, op: builtin.ModuleOp, rewriter: PatternRewriter):
        # Get module symbol table and attach accelerator op to it
        t = op.get_trait(SymbolTable)
        assert t is not None
        acc_string = self.acc_op.name_prop.string_value()
        if t.lookup_symbol(op, acc_string) is not None:
            raise RuntimeError(
                f"Cannot insert op: @{acc_string}, already present in symbol table."
            )
        t.insert_or_update(op, self.acc_op)


@dataclass(frozen=True)
class InsertAccOp(ModulePass):
    name = "insert-acc-op"

    accelerator: str  # accelerator name in registry

    """
    Parameterized pass that inserts an acc2.AcceleratorOp in the IR.
    The pass does a lookup in compiler/accelerators/registry.py

    Then the pass inserts the AcceleratorOp that is generated by the
    selected accelerator.

    Pass can be called from CLI as e.g.:
        snax-opt -p insert-acc-op{accelerater=snax_hwpe_mult}
    """

    def apply(self, ctx: MLContext, op: builtin.ModuleOp) -> None:
        # Access registry to get the accelerator interface
        acc_info = AcceleratorRegistry().get_acc_info(self.accelerator)
        # With the interface, generate an appropriate acc op
        acc_op = acc_info().generate_acc_op()
        # Use the get
        PatternRewriteWalker(InsertAcceleratorOpPattern(acc_op)).rewrite_module(op)
