from util.snake.configs import get_snax_gemmx_config

config_matmul = get_snax_gemmx_config()

config = get_snax_gemmx_config()


module snax_rules:
    snakefile:
        "../../util/snake/snax.smk"
    config:
        config


use rule * from snax_rules exclude snax_opt_mlir, simulate as snax_*


tests = ["matmul"]
systems = ["mat"]
archs = ["full"]
# banks = ['1', '2', '4', '8', '16', '32', '64', '128']
banks = ['8','16', '32', '64', '128']
# banks = ['16']


# Rules
rule all:
    input:
        "plot.pdf",


rule generate_plot:
    input:
        expand("{file}_summary.txt", file=tests),
    output:
        "plot.pdf",
    shell:
        "python plot.py"


rule extract_cycles:
    input:
        expand("{file}_sys{sys}_arch{arch}_bank{bank}_traces.json", file="{file}", sys=systems, bank=banks, arch=archs),
    output:
        "{file}_summary.txt",
    shell:
        "python extract_cycles.py {output} {input}"


rule simulate:
    input:
        "{file}_sys{sys}_arch{arch}.x",
    output:
        temp(
            expand(
                "{file}_sys{sys}_arch{arch}_bank{bank}_trace_chip_{num_chips:02d}_hart_{num_harts:05d}.dasm",
                file=["{file}"],
                sys=["{sys}"],
                arch=["{arch}"],
                bank=["{bank}"],
                num_chips=range(config["num_chips"]),
                num_harts=range(config["num_harts"]),
            ),
        ),
    log:
        temp("{file}_sys{sys}_arch{arch}_bank{bank}.vltlog"),
    params:
        vltsim=config_matmul["vltsim"],
    shell:
#        "vlt_fixed_cache_{wildcards.arch}/snitch_cluster_{wildcards.bank}_banks.vlt --prefix-trace={wildcards.file}_sys{wildcards.sys}_arch{wildcards.arch}_bank{wildcards.bank}_ {input}  2>&1 | tee {log}"
#        "../vlt_regular_array_size_test/new_16_8_8.vlt --prefix-trace={wildcards.file}_sys{wildcards.sys}_arch{wildcards.arch}_bank{wildcards.bank}_ {input}  2>&1 | tee {log}"
        "../vlt_fixed_cache_performance_banks_test/{wildcards.bank}_banks.vlt --prefix-trace={wildcards.file}_sys{wildcards.sys}_arch{wildcards.arch}_bank{wildcards.bank}_ {input}  2>&1 | tee {log}"

rule generate_matmul:
    output:
        "matmul_sys{sys}_arch{arch}.mlir",
    wildcard_constraints:
        sys="|".join(systems),
        arch="|".join(archs),
    shell:
        "python matmul.py --m 128 --n 128 --k 128 --output {output}"
        #"python matmul.py --m 48 --n 72 --k 80 --output {output}"
        #"python matmul.py --m 40 --n 56 --k 72 --output {output}"
        #"python matmul.py --m 560 --n 360 --k 168 --output {output}"
        # "python matmul.py --m 16 --n 8 --k 16 --output {output}"

def get_snax_config(wildcards):
    if wildcards.arch == "full":
        return "../../util/ssot/snax_gemmx.yaml"
    else:
        return "../../util/ssot/snax_gemmx_old.yaml"

def get_extra_flags(wildcards):
    if wildcards.arch == "full":
        #return "--fixed-cache-schedule"
        return ""
    else:
        return ""

rule compile_snax:
    input:
        "{file}_sys{sys}_arch{arch}.mlir",
    output:
        temp("{file}_sys{sys}_arch{arch}.ll.mlir"),
    params:
        snaxconfig=get_snax_config,
        extra_flags=get_extra_flags,
    shell:
        "{config[snaxc]} -c {params.snaxconfig} --add-mcycle {params.extra_flags} -o {output} {input}"


def get_linked_files(wildcards):
    return [f"{wildcards.file}_sys{wildcards.sys}_arch{wildcards.arch}.o", "main_2d_i8.o"]


rule link_snax_binary:
    input:
        get_linked_files,
    output:
        "{file}_sys{sys}_arch{arch}.x",
    shell:
        "{config[ld]} {config[ldflags]} {input} -o {output}"
