from util.snake.configs import get_snax_xdma_config

config = get_snax_xdma_config()


module snax_rules:
    snakefile:
        "../../util/snake/snax.smk"
    config:
        config


use rule * from snax_rules exclude snax_opt_mlir as snax_*


rule compile_snax:
    """
    Apply various transformations snax-opt on mlir files.
    Options controlled with `snaxoptflags` defined in config.
    """
    input:
        "{file}.mlir",
    output:
        temp("{file}.ll.mlir"),
    shell:
        "{config[snaxc]} -c {config[snaxc-config]} -o {output} {input}"


files = ["maxpool", "avgpool"]


# Rules
rule all:
    input:
        expand("{file}_traces.json", file=files),


# rule generate_maxpool:
#     output:
#         temp("maxpool.mlir"),
#     script:
#         "maxpool.py"

rule generate_avgpool:
    output:
        temp("avgpool.ppp.mlir"),
    script:
        "avgpool.py"

rule tosa_to_kernel:
    input:
        "avgpool.ppp.mlir",
    output:
        temp("avgpool.mlir"),
    shell:
        "snax-opt -p convert-tosa-to-kernel -o {output} {input}"


rule link_snax_binary:
    input:
        "{file}.o",
        "main.o",
    output:
        temp("{file}.x"),
    shell:
        "{config[ld]} {config[ldflags]} {input} -o {output}"
