from util.snake.configs import get_asplos_matmul_config
from util.snake.configs import get_asplos_matvec_config

import os

config_matmul = get_asplos_matmul_config()

config = get_asplos_matmul_config()

rule plot_figure:
    input:
        "summary.txt"
    output:
        "plot.svg",
    script:
        "plot.py"

module snax_rules:
    snakefile:
        "../../util/snake/snax.smk"
    config:
        config


use rule * from snax_rules exclude snax_opt_mlir as snax_*

rule all:
    input:
        "summary.txt"

rule generate_convs:
    output:
        "conv_1.mlir"
    shell:
        "python generate_tiled_convs.py"

rule compile_snax:
    input:
        "{file}.mlir",
    output:
        temp("{file}.ll.mlir"),
    shell:
        "{config[snaxc]} -c {config[snaxc-config]} --layout default -o {output} {input}"


def get_linked_files(wildcards):
    if "conv" in wildcards.file:
        return [f"{wildcards.file}.o", "main_4d_i8.o"]
    else:
        return [f"{wildcards.file}.o", "main_2d_i8.o"]


rule link_snax_binary:
    input:
        get_linked_files,
    output:
        "{file}.x",
    shell:
        "{config[ld]} {config[ldflags]} {input} -o {output}"
