from util.snake.cva6_flags import get_cva6_flags
from util.snake.flags import get_default_flags

from util.snake.configs import get_snax_gemmx_config

snitch_config = get_snax_gemmx_config()

cva6_flags = get_cva6_flags("../../hemaia_sw")

rule all:
  input:
    "host.o",
    "device.o",

rule compile_host:
    input:
        "host.c",
    output:
        temp("host.o"),
    shell:
        "clang {cva6_flags[cflags]} -c {input} -o {output}"

rule compile_device:
    input:
        "device.c",
    output:
        temp("device.o"),
    shell:
        "clang {snitch_config[cflags]} -c {input} -o {output}"

rule link_compile_host_partial:
    """
    Link host without device content to find address location of snitch_main.
    """
    input:
        "host.o"
    output:
        temp("host.part.elf")
    shell:
        "clang {cva6_flags[ldflags]} -o {output} {input} ../../hemaia_sw/target/sw/host/runtime/start.S"

rule origin_ld:
    input:
        "host.part.elf"
    output:
        "origin.ld"
    shell:
        r"""
        RELOC_ADDR=$(llvm-objdump -t {input} | grep snitch_main | cut -c9-16)
        echo "L3_ORIGIN = 0x$RELOC_ADDR;" > {output}
        """

rule link_device:
    input:
        "device.o",
        "origin.ld"
    output:
        "device.elf"
    shell:
        "clang {snitch_config[ldflags]} -T {input[1]} -o {output} {input[0]}"
