rule all:
    input:
        "addf.ll.mlir",


rule run_phs:
    input:
        "addf.mlir",
        "transform_schedule.mlir",
        "test_software.mlir",
    output:
        "addf.ll.mlir",
        "acc1_array.sv",
    shell:
        "phsc {input[0]} {input[1]} --software-file {input[2]} -o {output[0]} --output-hardware {output[1]} --debug"
