name: Build and run kernels

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-run-kernels:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/kuleuven-micas/snax-mlir:main
    steps:
      - uses: actions/checkout@v3
      - name: Install snax compiler
        run: |
          /opt/python3.11/bin/python3 -m pip install -e .
      - name: Build and run kernel simple mult
        run: |
          export PATH=/opt/python3.11/bin:$PATH
          make allrun
        working-directory: kernels/simple_mult
      - name: Build and run kernel simple copy
        run: |
          export PATH=/opt/python3.11/bin:$PATH
          make allrun
        working-directory: kernels/simple_copy
