name: Build and run kernels

on:
  push:
    branches:
      - main
    ignore-paths:
      - 'container/Dockerfile'
      - 'requirements.txt'
  pull_request:
    ignore-paths:
      - 'container/Dockerfile'
      - 'requirements.txt'
  workflow_run:
    workflows: ["build-docker"]
    types:
      - completed

jobs:
  figure-out-container-tag:
    runs-on: ubuntu-latest
    outputs:
      container-tag: ${{ steps.set-var.outputs.container-tag }}
    steps:
      - name: Set output
        id: set-var
        run: |
          echo "Setting Container tag"
          echo "event name: ${{ github.event_name }}"
          echo "github.ref: ${{ github.ref }}"
          echo "event.number: ${{ github.event.number }}"
          if [ "${{ github.event_name }}" == "workflow_run" ] && [ "${{github.ref}}" != "refs/heads/main" ]; then
            echo "container-tag=pr-${{github.event.number}}"
            echo "container-tag=pr-${{github.event.number}}" >> $GITHUB_OUTPUT
          else
            echo "container-tag=main"
            echo "container-tag=main" >> $GITHUB_OUTPUT
          fi

  build-and-run-kernels:
    needs: figure-out-container-tag
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/kuleuven-micas/snax-mlir:${{ needs.figure-out-container-tag.outputs.container-tag }}
    steps:
      - uses: actions/checkout@v3
      - name: Install snax compiler
        run: |
          /opt/python3.11/bin/python3 -m pip install -e .
      - name: Reinstall pip modules from requirements
        run: |
          /opt/python3.11/bin/python3 -m pip install -r requirements.txt
      - name: Build and run kernel simple mult
        run: |
          export PATH=/opt/python3.11/bin:$PATH
          make allrun
        working-directory: kernels/simple_mult
      - name: Build and run kernel simple copy
        run: |
          export PATH=/opt/python3.11/bin:$PATH
          make allrun
        working-directory: kernels/simple_copy
      - name: Build and run kernel simple_matmul
        run: |
          export PATH=/opt/python3.11/bin:$PATH
          make allrun
        working-directory: kernels/simple_matmul
