from util.snake.configs import get_snax_alu_config

config = get_snax_alu_config()


module snax_rules:
    snakefile:
        "../../util/snake/snax.smk"
    config:
        config


use rule * from snax_rules exclude snax_opt_mlir as snax_*


rule compile_snax:
    """
    Apply various transformations snax-opt on mlir files.
    Options controlled with `snaxoptflags` defined in config.
    """
    input:
        "{file}.mlir",
    output:
        temp("{file}.ll.mlir"),
    shell:
        "{config[snaxc]} --debug -c {config[snaxc-config]} -o {output} {input}"


files = ["streamer_add", "streamer_add_stream"]


# Rules
rule all:
    input:
        expand("{file}_traces.json", file=files),


from gendata import create_data_files


rule generate_data:
    output:
        "data.c",
        "data.h",
    run:
        create_data_files()


rule compile_simple_main:
    input:
        "main.c",
        "data.o",
    output:
        temp("main.o"),
    shell:
        "{config[cc]} {config[cflags]} -c {input} -o {output}"


rule link_snax_binary:
    input:
        "{file}.o",
        "data.o",
        "main.o",
    output:
        "{file}.x",
    shell:
        "{config[ld]} {config[ldflags]} {input} -o {output}"
