from util.snake.configs import get_snax_mac_config

config = get_snax_alu_config()
config["snaxoptflags"] = ",".join(
    [
        "insert-accfg-op{accelerator=snax_alu}"
        "convert-linalg-to-kernel"
        "dispatch-kernels",
        "test-insert-debugs",
        "set-memory-space",
        "set-memory-layout",
        "test-insert-debugs",
        "realize-memref-casts",
        "reuse-memref-allocs",
        "insert-sync-barrier",
        "dispatch-regions",
        "convert-linalg-to-stream",
        "convert-stream-to-snax-stream",
        "convert-linalg-to-accfg",
        "convert-accfg-to-csr",
        "snax-copy-to-dma",
        "memref-to-snax",
        "snax-to-func",
        "test-debug-to-func",
        "clear-memory-space",
    ]
)


module default_rules:
    snakefile:
        "../../util/snake/default_rules.smk"
    config:
        config


use rule * from default_rules as default_*


# Rules
rule all:
    input:
        "streamer_add.x",
        "streamer_add_stream.x",


rule generate_data:
    output:
        "data.c",
        "data.h",
    script:
        "gendata.py"
